### ISSUE TITLE
Documentation website not accessible anymore

### ISSUE THREAD

**Issue by alexisthual** [b-zurg/react-collapse-pane#141]
Thank you for the great library!
It seems that there is a problem with the documentation right now. I get the following error message on Chrome:

```
Your connection is not private
Attackers might be trying to steal your information from collapse-pane.zurg.dev (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
```

![Screenshot from 2022-01-04 17-10-10](https://user-images.githubusercontent.com/13835654/148088684-799af869-2f8f-4fa8-828e-176a8115bfd0.png)

**Comment by alexkreidler** [comment]
Luckily, the docs are available via Markdown in [repository](https://github.com/b-zurg/react-collapse-pane/tree/master/docs), or as HTML [here](https://raw.githack.com/b-zurg/react-collapse-pane/master/docs/index.html#/). But it would be great to fix the Storybook deployment too so new users could check out the demos.

**Comment by b-zurg** [comment]
yeah totally true.  I lost my domain due to a sad payment issue from google domains. I'll move the site sometime soon.

**Comment by b-zurg** [comment]
Now resolved in latest release
