### ISSUE TITLE
`styled-components` shouldn't be a dependency.

### ISSUE THREAD

**Issue by kadoshms** [b-zurg/react-collapse-pane#172]
Hello there, thanks for the great library.

I noticed that `styled-components` is a library dependency, which is not a good practice.
Please mind the official styled-components docs https://styled-components.com/docs/faqs#marking-styledcomponents-as-external-in-your-package-dependencies.

In addition, to me it feels a bit odd that `material-ui` is a depednency only for the sake of transitions. Are there any slimer approaches?

Thanks.

**Comment by b-zurg** [comment]
There definitely are. You're totally right I'll move it to peer dependencies in a new release.

As for transitions, I am thinking of redoing the entire approach and not including even styled components but rather focusing on the basics with an option to add one's own css or transitions as they want.

**Comment by b-zurg** [comment]
Now resolved in latest release

**Comment by mkeo99** [comment]
Hey @b-zurg, can you clarify what version it was fixed in?
