### ISSUE TITLE
Missing definition for Nullable<T> in SplitPane/index.tsx

### ISSUE THREAD

**Issue by hst44** [b-zurg/react-collapse-pane#24]
Nullable<T> is not defined in src/components/SplitPane/index.tsx which causes builds to fail when including a SplitPane via npm.  Results in:

ERROR in ...\node_modules\react-collapse-pane\dist\components\SplitPane\index.d.ts
(8,35): error TS2304: Cannot find name 'Nullable'.
ERROR in ...\node_modules\react-collapse-pane\dist\components\SplitPane\index.d.ts
(34,22): error TS2304: Cannot find name 'Nullable'.

**Comment by b-zurg** [comment]
Oh! That's what I get for using a global type. 

I'll fix that today. I think you should be able to get it working by using `skiplibcheck` in the `tsconfig.json` of your project.

**Comment by b-zurg** [comment]
@hst44 did the latest release resolve the issue?

**Comment by hst44** [comment]
There isnt an error about Nullable<T> anymore, but the change introduced a new error:

ERROR in ...\node_modules\react-collapse-pane\dist\components\SplitPane\index.d.ts
(2,26): error TS2307: Cannot find module '../../types/utilities' or its corresponding type declarations.

**Comment by b-zurg** [comment]
Thanks for reporting.  The source of this issue was that `*.d.ts` files are not emitted during output.  I'll rename the type declaration file to be a normal `*.ts` file and have a fix released in a sec.

**Comment by hst44** [comment]
Great! thanks for the quick fix!

**Comment by b-zurg** [comment]
No worries :)

@all-contributors please add @hst44 for bug

**Comment by b-zurg** [comment]
Release v1.3.10

Please confirm if it fixes the issue

**Comment by hst44** [comment]
All fixed.  Thanks!
