### ISSUE TITLE
Can the SplitPane fit the size of its containing element?

### ISSUE THREAD

**Issue by leoniedarois** [b-zurg/react-collapse-pane#41]
Hello,

Is there a way to make it so that the SplitPane fits the size of its parent?
I have a container that has a defined size and I would like to use your component in it. But I can't make it fit the size of the parent: it grows out of it until it has the same size of the frame.
I made this [sandboxe ](https://codesandbox.io/s/react-collapse-pane37-forked-2tu2i?file=/src/App.js) to explain my problem.
I would need the splitpane to have the same width of the green square, and a height that does not goes out of its containing div, how could I do that?
And as you can see, the footer is put under the header instead of under the splitpane, is it possible to do otherwise?

Thanks for your time !

**Comment by yandexphp** [comment]
Hello, your problem is not really component related. Just add styles and you will be happy :)

![image](https://user-images.githubusercontent.com/29909911/98431872-82db3080-20e3-11eb-8f5f-4a063c394ddc.png)

**Comment by leoniedarois** [comment]
Thank you so much !

**Comment by b-zurg** [comment]
Sorry it took me so long to give this a look!  Seems like it's resolved but if it's not please comment and I'll investigate :)
