### ISSUE TITLE
Does collapseDirection work?

### ISSUE THREAD

**Issue by JeremyGrieshop** [b-zurg/react-collapse-pane#75]
I can't seem to get it to work with the collapseOptions.  Codesandbox:

https://codesandbox.io/s/react-collapse-pane-down-hrov2?file=/src/App.js

**Comment by godsamit** [comment]
I think the prop name is changed to "collapse".

**Comment by JeremyGrieshop** [comment]
> I think the prop name is changed to "collapse".

collapse tells it to show the collapse button.  collapseDirection is supposed to control which direction.

**Comment by godsamit** [comment]
No... read the source code. the prop name has been changed.
https://github.com/b-zurg/react-collapse-pane/blob/884670946aa1f9af1ad4e4a2541f80239414ffcf/src/components/SplitPane/index.tsx#L46

**Comment by JeremyGrieshop** [comment]
Ah, thank you, @godsamit.  The documentation example shows otherwise.
